@startuml

class Student {
    - name: String
    - age: int
    + getName(): String
    + setName(String): void
    + getAge(): int
    + setAge(int): void
    + display(): String
}

class StudentManager {
    - Student[] students
    + add(Student): void
    + find(String): void
    + displayAll(): void
}

class StudentManagerTest {
    + {static} main(String[]): void
}

Student <- StudentManager
Student <.. StudentManagerTest
StudentManager <. StudentManagerTest

@enduml